global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  
scrape_configs:
  - job_name: 'otel-collector-metrics'
    # Use o nome do serviço do Docker Compose e a porta interna do Collector
    static_configs:
      - targets: ['otel-collector:9464'] 